#
# interactive login
#

# setup bash
source "$HOME/.bashrc"


if is-start-session; then
   source "$HOME/.bash/session.sh"
fi


source "$HOME/.bash/aliases.sh"

if [ -n "$SETUP_PROMPTS" ]; then
   source "$HOME/.bash/prompt.sh"
fi


[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

for bcfile in ~/.completion.d/*.bash ; do
    source $bcfile
done

complete -cf sudo