#
# non-interactive login
#

# config bash settings
source "$HOME/.bash/bashrc"


PATH="$HOME/.local/bin:$PATH"

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi


source "$HOME/.bash/environment.sh"
source "$HOME/.bash/commands.sh"

if [ -f "$HOME/.environment" ]; then
   source "$HOME/.environment"
fi

if [ -f "$HOME/.local_profile" ]; then
    source "$HOME/.local_profile"
fi


if is-login-shell; then
   source "$HOME/.bash/login.sh"
fi



if [ -n "$SETUP_PYENV" ]; then
    eval "$(pyenv init -)"
    pyenv virtualenvwrapper_lazy
fi
