#

# Configure bashrc for interactive use
#


bind "set completion-ignore-case on"
bind "set bell-style none"


# append to the history file, don't overwrite it
shopt -s histappend


# check the window size after each command
shopt -s checkwinsize


# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar


# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
